{{- if .Values.operator.clusterRoleBinding.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "resource-booking-operator.fullname" . }}
  labels:
    {{- include "resource-booking-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "resource-booking-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "resource-booking-operator.serviceAccountName" . }}
  namespace: {{ .Values.operator.namespace }}
{{- end }} 