apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-booking-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resource-booking-operator
subjects:
  - kind: ServiceAccount
    name: resource-booking-operator
    namespace: {{ .Release.Namespace }} 