{{- if and .Values.operator.namespace (not (lookup "v1" "Namespace" "" .Values.operator.namespace)) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.operator.namespace }}
  labels:
    {{- include "resource-booking-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
    app.kubernetes.io/component: manager
{{- end }} 