{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "resource-booking-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "resource-booking-operator.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "resource-booking-operator.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
{{- end }} 