apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-booking-operator
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::163217415796:role/ResourceBookingOperatorRole" 