{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "resource-booking-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "resource-booking-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "resource-booking-operator.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
  endpoints:
  - port: metrics
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    path: {{ .Values.serviceMonitor.path }}
{{- end }} 