{{- if .Values.operator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "resource-booking-operator.serviceAccountName" . }}
  namespace: {{ .Values.operator.namespace }}
  labels:
    {{- include "resource-booking-operator.labels" . | nindent 4 }}
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }} 