{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "resource-booking-operator.namespace" . }}
  labels:
    {{- include "resource-booking-operator.labels" . | nindent 4 }}
    {{- with .Values.namespace.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }} 