apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource-booking-operator.fullname" . }}-metrics-service
  namespace: {{ include "resource-booking-operator.namespace" . }}
  labels:
    {{- include "resource-booking-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  ports:
  {{- if .Values.authProxy.enabled }}
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  {{- else }}
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  {{- end }}
  selector:
    {{- include "resource-booking-operator.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager 