{{- if .Values.rbac.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "resource-booking-operator.serviceAccountName" . }}
  namespace: {{ include "resource-booking-operator.namespace" . }}
  labels:
    {{- include "resource-booking-operator.labels" . | nindent 4 }}
    {{- with .Values.rbac.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }} 